version: 2
updates:
    # npm production dependencies
    - package-ecosystem: "npm"
      directory: "/"
      target-branch: "dev"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 10
      rebase-strategy: "auto"
      allow:
          - dependency-type: "production"
      labels:
          - "dependencies"
          - "dependencies:production"

    # npm development dependencies
    - package-ecosystem: "npm"
      directory: "/"
      target-branch: "dev"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 10
      rebase-strategy: "auto"
      allow:
          - dependency-type: "development"
      labels:
          - "dependencies"
          - "dependencies:development"

    # GitHub Actions workflow dependencies
    - package-ecosystem: "github-actions"
      directory: "/"
      target-branch: "dev"
      schedule:
          interval: "weekly"
      labels:
          - "dependencies"
