name: Deploy with gh-pages
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
        types:
            - closed
jobs:
    build-and-deploy:
        name: "Master branch updated"
        if: github.event.pull_request.merged == true || github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build and Deploy
              run: |
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
              env:
                  ITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
