name: Deploy with gh-pages
on:
    pull_request:
        branches:
            - master
        types:
            - closed
jobs:
    build-and-deploy:
        name: "Master branch updated"
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/setup-node@v2
              with:
                  node-version: "16.x"
                  cache: "npm"
            - name: Deploy with gh-pages
              run: |
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
